---

dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

sudo: required

language: python

install:
  - pip install --upgrade tox

script:
  - tox

jobs:
  include:
    - stage: lint
      python: 3.7
      env:
        - TOXENV=lint

    - stage: test
      python: 3.5
      env:
        - TOXENV=py35
    - stage: test
      python: 3.6
      env:
        - TOXENV=py36
    - stage: test
      python: 3.7
      env:
        - TOXENV=py37

    - stage: publish
      if: tag is present
      script:
        - pip install twine
        - make release
