---

dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

sudo: required

language: python

install:
  - pip install --upgrade tox

script:
  - tox

jobs:
  include:
    - stage: test
      python: 3.7
      env:
        - TOXENV=py37

    - stage: publish
      if: tag is present
      script:
        - pip install twine
        - make release
